remote: true

experienceLevel:
  internship: true
  entry: true
  associate: false
  mid-senior level: false
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: true
  part-time: false
  temporary: true
  internship: true
  other: true
  volunteer: true

date:
  all time: true
  month: true
  week: true
  24 hours: true

positions:
  - Software Tester
  - Quality Assurance Engineer
  - Test Automation Engineer
  - Software Developer
  - University Graduate
  - Software Engineer
  - Entry Level Software Engineer
  - Web Designer
  - Web Developer
  - Front End Developer
  - Back End Developer
  - Full Stack Developer
  - Junior Developer
  - Junior Software Developer
  - Junior Web Developer
  - Junior Front End Developer
  - Junior Back End Developer
  - Junior Full Stack Developer
  - Junior Software Engineer

locations:
  - USA

distance: 100

companyBlacklist:
   
titleBlacklist:
